Draft deployment guidelines
deepset-ai/hayhooks pull request #46
Opened 2024-12-05 11:49 UTC by mpangrazzi

The purpose of this document is simply to make people more aware of how pipelines can be deployed and called on Hayhooks in different environment (single vs multiple workers).

2024-12-06 14:13 UTC, julian-risch requested changes
Looks quite good to me already. I just made four tiny suggestions and then it's ready to be merged from my side. Let's wait for Stefano's review on Monday.

2024-12-06 14:13 UTC, julian-risch commented on docs/deployment_guidelines.md
> +- If your pipeline is doing **mainly CPU-bound operations** (like computating embeddings), the GIL (Global Interpreter Lock) will prevent the worker from handling concurrent requests, so they will be
```suggestion
- If your pipeline is doing **mainly CPU-bound operations** (like computing embeddings), the GIL (Global Interpreter Lock) will prevent the worker from handling concurrent requests, so they will be queued.
```

2024-12-06 14:13 UTC, julian-risch commented on docs/deployment_guidelines.md
> +For example, if you enough cores to run 4 workers, you can use the following command:
```suggestion
For example, if you have enough cores to run 4 workers, you can use the following command:
```

2024-12-06 14:13 UTC, julian-risch commented on docs/deployment_guidelines.md
> +This vertical scaling approach allows you to handle more concurrent requests (according the available resources).
```suggestion
This vertical scaling approach allows you to handle more concurrent requests (depending on available resources).
```

2024-12-06 14:13 UTC, julian-risch commented on docs/deployment_guidelines.md
> +In a multi-worker environment (for example on a Kubernetes `Deployment`) you typically have a `LoadBalancer` Service which distributes the traffic to a number of `Pod`s running the application (using
```suggestion
In a multi-worker environment (for example on a Kubernetes `Deployment`) you typically have a `LoadBalancer` Service, which distributes the traffic to a number of `Pod`s running the application (using `hayhooks run` command).
```

2024-12-06 14:52 UTC, mpangrazzi commented
@julian-risch thanks! Yes, let's wait for @anakin87 review. 

Probably it could worth to add an end-to-end example or tutorial (build a simple pipeline, serialise it to YAML, run Hayhooks and run it), WDYT?

2024-12-09 11:39 UTC, anakin87 approved these changes
I like the guidelines.
They should be understandable for someone familiar with these topics and provide a good introduction to others.

- We should probably link them (or copy them?) in our docs: https://docs.haystack.deepset.ai/docs/hayhooks; https://docs.haystack.deepset.ai/docs/deployment
- An end-to-end example would be helpful
-  Keep in mind that there is an (unmaintained) demo based on Hayhooks: https://github.com/deepset-ai/haystack-demos/tree/main/qdrant_indexing

2024-12-09 11:49 UTC, mpangrazzi commented
@anakin87 ah, didn't know about that existing demo. I think it would be good to have a similar one here, e.g. on an `examples` folder or so. I can take care of it.

2024-12-10 13:04 UTC, julian-risch approved these changes

2024-12-10 15:26 UTC, mpangrazzi commented
@julian-risch @anakin87 I'll merge this and add the examples in a separate PR

2024-12-10 15:26 UTC, merged